###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '8001:8025'

    mysql:
        image: 'mysql:8.0'
        working_dir: ''
        volumes:
            - '.:/var/www/html:'
        environment:
            - MYSQL_ROOT_PASSWORD=example
            - MYSQL_DATABASE=database
            - MYSQL_USER=example
            - MYSQL_PASSWORD=example
        ports:
            - '8002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: ''
        volumes:
            - '.:/var/www/html:'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: ''
        volumes:
            - '.:/var/www/html:'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
